### ISSUE TITLE
http://lc100e.github.io/manual returns not found

### ISSUE THREAD

**Issue by MoridinBG** [LC100E/lc100e.github.io#1]
<img width="1392" alt="Screenshot 2021-11-28 at 16 21 17" src="https://user-images.githubusercontent.com/1854038/143771865-3b4ec532-c43a-4723-b303-f625a654cafe.png">

Direct links to PDF like http://lc100e.github.io/manual/rm/rm616e/m_ac_0028.pdf, which used to work don't work anymore either

**Comment by LC100E** [comment]
Hi Ivan,

The url is now lc100e.github.io

Thanks
Chris

0419-269-741
LinkedIn/Chris-Cullin <https://www.linkedin.com/in/chris-cullin>

**Comment by LC100E** [comment]
I have just updated the README.

Chris

0419-269-741
LinkedIn/Chris-Cullin <https://www.linkedin.com/in/chris-cullin>

**Comment by LC100E** [comment]
new file structure implemented and README updated.
